"""empty message

Revision ID: 1eede2ac7f60
Revises: a2d58037b121
Create Date: 2022-02-17 20:24:03.152193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eede2ac7f60'
down_revision = 'a2d58037b121'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('votes_book_id_fkey', 'votes', type_='foreignkey')
    op.drop_column('votes', 'book_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('votes_book_id_fkey', 'votes', 'books', ['book_id'], ['id'])
    # ### end Alembic commands ###
