"""empty message

Revision ID: 38d3bd7aa748
Revises: 1eede2ac7f60
Create Date: 2022-02-17 20:32:11.677949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38d3bd7aa748'
down_revision = '1eede2ac7f60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('comment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'books', 'votes', ['comment_id'], ['comment_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'comment_id')
    # ### end Alembic commands ###
