"""empty message

Revision ID: 6f434e019ab9
Revises: 38d3bd7aa748
Create Date: 2022-02-17 20:42:55.751846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f434e019ab9'
down_revision = '38d3bd7aa748'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('books_comment_id_fkey', 'books', type_='foreignkey')
    op.drop_column('books', 'comment_id')
    op.add_column('votes', sa.Column('book_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'votes', 'books', ['book_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.drop_column('votes', 'book_id')
    op.add_column('books', sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('books_comment_id_fkey', 'books', 'votes', ['comment_id'], ['comment_id'])
    # ### end Alembic commands ###
